import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import NavBar from "@/app/ui/NavBar";
import styles from "./ui/global.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased ${styles.body}`}>
        <main>
          <NavBar />
          {children}
        </main>
        <footer className={styles.footer}>
          {"Footer info here :)"}
        </footer>
      </body>
    </html>
  );
}
