import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import NavBar from "@/app/ui/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <main>
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
